# Generated by Django 5.0.7 on 2024-07-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_category_item_materialrequest_notification_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('shipped', 'shipped')], default='shipped', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
