# Generated by Django 5.0.7 on 2024-08-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_rename_message_notification_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Manager', 'manager'), ('Registeror', 'registeror'), ('Engineer', 'Engineer'), ('Staff', 'staff'), ('Admin', 'Admin'), ('Other', 'Other')], default='Engineer', max_length=20),
        ),
    ]
