# Generated by Django 5.0.7 on 2024-08-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_materialrequest_user_alter_notification_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='MaterialRequest',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
