# Generated by Django 5.0.7 on 2024-08-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_notification_delete_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='quantity_requested',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Manager', 'manager'), ('Staff', 'staff'), ('Admin', 'Admin'), ('Other', 'Other')], default='Staff', max_length=20),
        ),
    ]
